package ar.edu.unlam.pb1;

public enum OpcionDeMenu {
	
	AGREGAR_PROPIEDAD, MODIFICAR_PROPIEDAD, AGREGAR_CLIENTE, OBTENER_LISTADO_POR_PRECIO, OBTENER_LISTADO_POR_UBICACION, 
	BUSCAR_POR_PRECIO, BUSCAR_POR_UBICACION, REALIZAR_VENTA, REALIZAR_ALQUILER, SALIR;

}
